version: "3"
services:
  nginx:
    image: nginx:1.12-alpine
    volumes:
    - ./nginx/piplin.template:/etc/nginx/conf.d/piplin.template
    - ./src/:/var/www/piplin/
    ports:
    - "80:80"
    links:
    - 'php:piplin-php'
    environment:
    - NGINX_HOST=piplin.app
    - NGINX_PORT=80
    command: /bin/ash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/piplin.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql:
    image: mysql:5.6
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_DATABASE: piplin
      MYSQL_USER: piplin
      MYSQL_PASSWORD: piplinpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - piplin-mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always

  redis:
    image: redis:3.2-alpine
    expose:
      - "6379"
    volumes:
      - piplin-redis:/data
    restart: always

  php:
    build: ./php
    volumes:
      - ./php/supervisor/piplin.conf:/etc/supervisor/conf.d/piplin.conf
      - ./src/:/var/www/piplin/
    ports:
      - 7001:7001
    links:
      - 'mysql:piplin-mysql'
      - 'redis:piplin-redis'
    depends_on:
      - mysql
      - redis
    restart: on-failure

volumes:
  piplin-mysql:
  piplin-redis: